- hosts: all
  become: yes
  tasks:
    - name: Set up directory for roles
      file:
        path: /etc/ansible/roles
        state: directory
        mode: "0755"

    - name: Clone Ansible roles repository
      git:
        repo: "{{ git_repository }}"
        dest: /etc/ansible/roles
        version: "{{ git_branch }}"
      environment:
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"

  vars:
    git_repository: "https://github.com/ppaciekq/Ansible_roles.git"
    git_branch: "main"
